server:
  port: 8352
spring:
  application:
    name: eureka-service-2-1
eureka:
  client:
    service-url:
      defaultZone: http://localhost8305:8305/eureka/
    instance:
      instance-id: ${spring.application.name}
services: >
  ,eureka-service-3-1