server:
  port: 8332
spring:
  application:
    name: nacos-service-sentinel-cluster-client
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:9080