server:
  port: 8304
spring:
  application:
    name: eureka-service-consumer
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    healthcheck:
      enabled: true
    enabled: true
    service-url:
      defaultZone: http://localhost8305:8305/eureka/, http://localhost8306:8306/eureka/
    instance:
      instance-id: eureka-service-consumer # ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      perfer-ip-address: true
      metadataMap:
        zone: shanghai
    perferSameZoneEureka: false
    refresh:
      enable: true
    tls:
      enabled: false
      key-store: <path-of-key-store>
      key-store-type: PKCS12
      key-store-password: <key-store-password>
      key-password: <key-password>
      trust-store: <path-of-trust-store>
      trust-store-type: PKCS12
      trust-store-password: <trust-store-password>
    eureka-connection-idle-timeout-seconds: 30 # 心跳
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 8
    eureka-server-total-connections: 200